config:
  - host: 192.168.1.60
    username: administrator@vsphere.local
    password: Abcd123$
    Name: VCenter4
    IngestToken: rb2yT1_ej4yXYkIdSQzp_w
    MORSyncInterval: 300
    MetricSyncInterval: 300
    IncludeMetrics:
      host:
        - random.test.metric
      cluster:
        - mem.usage.average
