#!/usr/bin/env python

DEFAULT_METRIC_SYNC_INTERVAL = 5 * 60  # 5 minutes

DEFAULT_MOR_SYNC_INTERVAL = 5 * 60  # 5 minutes

DEFAULT_TIMEOUT = 60

DEFAULT_COLLECTION_INTERVAL = 20  # 20 seconds

INVENTORY_SYNC_TIMEOUT = 60  # 1 minute

METADATA_METRIC_NAME = "signalfx_vsphere_metadata"

METRIC_SOURCE = "vsphere"

VERBOSITY_LEVELS = (1, 2, 3, 4)

SIGNALFX_INGEST_TOKEN = 'rb2yT1_ej4yXYkIdSQzp_w'
