version: '2'
jobs:
  build:
    docker:
      - image: ubuntu:trusty
    working_directory: ~/code
    steps:
      - setup_remote_docker
      - run:
          name: Install Python pip
          command: |
            set -x
            VER="17.03.0-ce"
            apt-get update -q
            apt-get install -yq curl python3-pip
      - checkout
      - run:
          name: Run basic tests
          working_directory: ~/code
          command: |
            pip3 install -r test_requirements.txt
            bash verify.sh
